// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBYtBPF4xRemNqw9LjbHbxz9Rs_Dw5JoA',
    appId: '1:949159400118:web:5c1f50dc5b0a66b2970c17',
    messagingSenderId: '949159400118',
    projectId: 'photosurfing-8eca8',
    authDomain: 'photosurfing-8eca8.firebaseapp.com',
    storageBucket: 'photosurfing-8eca8.appspot.com',
    measurementId: 'G-WKF1E6YCPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPorDyXEcwvy8JELLWNgLPEQQkUUiSibE',
    appId: '1:949159400118:android:937a8af54b5f3802970c17',
    messagingSenderId: '949159400118',
    projectId: 'photosurfing-8eca8',
    storageBucket: 'photosurfing-8eca8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-C6_NMK-Z8HdIW5OIgf3m7Jnt3bqzjBQ',
    appId: '1:949159400118:ios:b082c64a5645d997970c17',
    messagingSenderId: '949159400118',
    projectId: 'photosurfing-8eca8',
    storageBucket: 'photosurfing-8eca8.appspot.com',
    iosBundleId: 'com.example.photoSurfing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-C6_NMK-Z8HdIW5OIgf3m7Jnt3bqzjBQ',
    appId: '1:949159400118:ios:b082c64a5645d997970c17',
    messagingSenderId: '949159400118',
    projectId: 'photosurfing-8eca8',
    storageBucket: 'photosurfing-8eca8.appspot.com',
    iosBundleId: 'com.example.photoSurfing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBYtBPF4xRemNqw9LjbHbxz9Rs_Dw5JoA',
    appId: '1:949159400118:web:bf915bbf664185a1970c17',
    messagingSenderId: '949159400118',
    projectId: 'photosurfing-8eca8',
    authDomain: 'photosurfing-8eca8.firebaseapp.com',
    storageBucket: 'photosurfing-8eca8.appspot.com',
    measurementId: 'G-3SNV5P7N5F',
  );
}
